changelog_entry.yaml
setup.py

Bump policyengine-us to 0.190.3

Bump policyengine-us to 0.190.3

---

changelog_entry.yaml
setup.py

Bump policyengine-uk to 0.37.6

Bump policyengine-uk to 0.37.6

---

changelog_entry.yaml
policyengine_api/compute_api/compute_api.py

cc @MaxGhenis. Silly error on time parsing

Fix time parsing bug and remove debug statements

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.193.0

Bump policyengine-us to 0.193.0

---

changelog_entry.yaml
policyengine_api/compute_api/economy.py
setup.py

Bump policyengine-us to 0.193.1

Bump policyengine-us to 0.193.1

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.194.1

Bump policyengine-us to 0.194.1

---

changelog_entry.yaml
setup.py

Bump policyengine-uk to 0.38.0

Bump policyengine-uk to 0.38.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.194.2

Bump policyengine-us to 0.194.2

---

changelog_entry.yaml
setup.py

Bump policyengine-uk to 0.38.1

Bump policyengine-uk to 0.38.1

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.194.3

Bump policyengine-us to 0.194.3

---

changelog_entry.yaml
setup.py

Bump policyengine-uk to 0.38.2

Bump policyengine-uk to 0.38.2

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.199.6

Bump policyengine-us to 0.199.6

---

changelog_entry.yaml
setup.py

Bump policyengine-uk to 0.38.6

Bump policyengine-uk to 0.38.6

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.200.7

Bump policyengine-us to 0.200.7

---

changelog_entry.yaml
setup.py

Bump policyengine-canada to 0.23.0

Bump policyengine-canada to 0.23.0

---

changelog_entry.yaml
policyengine_api/api.py

Return /calculate results under the default structure

---

changelog_entry.yaml
policyengine_api/compute_api/economy.py

Fix UK economy outputs

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.203.8

Bump policyengine-us to 0.203.8

---

changelog_entry.yaml
setup.py

Bump policyengine-uk to 0.40.0

Bump policyengine-uk to 0.40.0

---

changelog_entry.yaml
setup.py

Bump policyengine-uk to 0.41.0

Bump policyengine-uk to 0.41.0

---

changelog_entry.yaml
setup.py

Bump policyengine-uk to 0.41.1

Bump policyengine-uk to 0.41.1

---

changelog_entry.yaml
setup.py

Bump policyengine-uk to 0.41.2

Bump policyengine-uk to 0.41.2

---

changelog_entry.yaml
setup.py

Bump policyengine-canada to 0.27.1

Bump policyengine-canada to 0.27.1

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.203.10

Bump policyengine-us to 0.203.10

---

changelog_entry.yaml
setup.py

Bump policyengine-canada to 0.29.0

Bump policyengine-canada to 0.29.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.205.1

Bump policyengine-us to 0.205.1

---

changelog_entry.yaml
setup.py

Bump policyengine-canada to 0.30.0

Bump policyengine-canada to 0.30.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.205.3

Bump policyengine-us to 0.205.3

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.207.0

Bump policyengine-us to 0.207.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.207.1

Bump policyengine-us to 0.207.1

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.207.2

Bump policyengine-us to 0.207.2

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.207.3

Bump policyengine-us to 0.207.3

---

changelog_entry.yaml
setup.py

Bump policyengine-canada to 0.31.0

Bump policyengine-canada to 0.31.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.208.0

Bump policyengine-us to 0.208.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.209.2

Bump policyengine-us to 0.209.2

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.209.3

Bump policyengine-us to 0.209.3

---

changelog_entry.yaml
setup.py

Bump policyengine-canada to 0.32.0

Bump policyengine-canada to 0.32.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.210.1

Bump policyengine-us to 0.210.1

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.211.0

Bump policyengine-us to 0.211.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.211.1

Bump policyengine-us to 0.211.1

---

changelog_entry.yaml
policyengine_api/endpoints/computed_household.py

Fix parameter parsing bug

---

changelog_entry.yaml
policyengine_api/endpoints/computed_household.py

Fix household impact bug

---

changelog_entry.yaml
setup.py

Bump policyengine-canada to 0.33.0

Bump policyengine-canada to 0.33.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.213.0

Bump policyengine-us to 0.213.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.213.1

Bump policyengine-us to 0.213.1

---

changelog_entry.yaml
setup.py

Bump policyengine-canada to 0.35.0

Bump policyengine-canada to 0.35.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.213.2

Bump policyengine-us to 0.213.2

---

changelog_entry.yaml
setup.py

Bump policyengine-canada to 0.36.0

Bump policyengine-canada to 0.36.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.213.3

Bump policyengine-us to 0.213.3

---

changelog_entry.yaml
setup.py

bump policyengine-ng

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.213.4

Bump policyengine-us to 0.213.4

---

changelog_entry.yaml
setup.py

Bump policyengine-canada to 0.38.0

Bump policyengine-canada to 0.38.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.214.0

Bump policyengine-us to 0.214.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.214.1

Bump policyengine-us to 0.214.1

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.214.2

Bump policyengine-us to 0.214.2

---

changelog_entry.yaml
setup.py

Bump policyengine-canada to 0.38.1

Bump policyengine-canada to 0.38.1

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.214.4

Bump policyengine-us to 0.214.4

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.215.1

Bump policyengine-us to 0.215.1

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.216.0

Bump policyengine-us to 0.216.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.217.0

Bump policyengine-us to 0.217.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.217.1

Bump policyengine-us to 0.217.1

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.218.0

Bump policyengine-us to 0.218.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.219.0

Bump policyengine-us to 0.219.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.220.1

Bump policyengine-us to 0.220.1

---

changelog_entry.yaml
setup.py

Bump policyengine-canada to 0.39.0

Bump policyengine-canada to 0.39.0

---

changelog_entry.yaml
setup.py

Bump policyengine-canada to 0.40.0

Bump policyengine-canada to 0.40.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.220.2

Bump policyengine-us to 0.220.2

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.220.3

Bump policyengine-us to 0.220.3

---

changelog_entry.yaml
gcp/compute_api/app.yaml
gcp/policyengine_api/app.yaml

Testing this out since I suspect we're bottlenecked by other things.

Reduce CPU counts

---

changelog_entry.yaml
setup.py

Bump policyengine-uk to 0.41.7

Bump policyengine-uk to 0.41.7

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.220.4

Bump policyengine-us to 0.220.4 and policyengine-uk

---

changelog_entry.yaml
setup.py

Bump policyengine-canada to 0.42.0

Bump policyengine-canada to 0.42.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.220.5

Bump policyengine-us to 0.220.5

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.222.1

Bump policyengine-us to 0.222.1

---

changelog_entry.yaml
setup.py

Bump policyengine-uk to 0.41.11

Bump policyengine-uk to 0.41.11

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.223.0

Bump policyengine-us to 0.223.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.224.0

Bump policyengine-us to 0.224.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.224.1

Bump policyengine-us to 0.224.1

---

changelog_entry.yaml
setup.py

Bump policyengine-uk to 0.42.0

Bump policyengine-uk to 0.42.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.225.0

Bump policyengine-us to 0.225.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.226.0

Bump policyengine-us to 0.226.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.227.0

Bump policyengine-us to 0.227.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.228.0

Bump policyengine-us to 0.228.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.229.0

Bump policyengine-us to 0.229.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.230.0

Bump policyengine-us to 0.230.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.230.1

Bump policyengine-us to 0.230.1

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.231.1

Bump policyengine-us to 0.231.1

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.231.2

Bump policyengine-us to 0.231.2

---

changelog_entry.yaml
setup.py
tests/compute_api/test_microdata.py

Bump policyengine-us to 0.234.0

Bump policyengine-us to 0.234.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.237.1

Bump policyengine-us to 0.237.1

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.238.0

Bump policyengine-us to 0.238.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.238.1

Bump policyengine-us to 0.238.1

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.239.1

Bump policyengine-us to 0.239.1

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.240.0

Bump policyengine-us to 0.240.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.241.0

Bump policyengine-us to 0.241.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.243.0

Bump policyengine-us to 0.243.0

---

changelog_entry.yaml
setup.py

Bump policyengine-canada to 0.42.1

Bump policyengine-canada to 0.42.1

---

changelog_entry.yaml
setup.py

Bump policyengine-uk to 0.43.0

Bump policyengine-uk to 0.43.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.247.0

Bump policyengine-us to 0.247.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.248.0

Bump policyengine-us to 0.248.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.250.0

Bump policyengine-us to 0.250.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.251.0

Bump policyengine-us to 0.251.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.259.0

Bump policyengine-us to 0.259.0

---

changelog_entry.yaml
setup.py

Bump policyengine-canada to 0.43.0

Bump policyengine-canada to 0.43.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.260.0

Bump policyengine-us to 0.260.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.261.1

Bump policyengine-us to 0.261.1

---

changelog_entry.yaml
setup.py

Bump policyengine-canada to 0.44.0

Bump policyengine-canada to 0.44.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.262.0

Bump policyengine-us to 0.262.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.263.0

Bump policyengine-us to 0.263.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.263.1

Bump policyengine-us to 0.263.1

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.263.2

Bump policyengine-us to 0.263.2

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.263.3

Bump policyengine-us to 0.263.3

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.263.4

Bump policyengine-us to 0.263.4

---

changelog_entry.yaml
setup.py

Bump policyengine-uk to 0.45.0

Bump policyengine-uk to 0.45.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.263.5

Bump policyengine-us to 0.263.5

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.264.0

Bump policyengine-us to 0.264.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.266.0

Bump policyengine-us to 0.266.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.267.0

Bump policyengine-us to 0.267.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.268.0

Bump policyengine-us to 0.268.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.271.0

Bump policyengine-us to 0.271.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.273.0

Bump policyengine-us to 0.273.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.275.0

Bump policyengine-us to 0.275.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.276.0

Bump policyengine-us to 0.276.0

---

changelog_entry.yaml
setup.py

Bump policyengine-canada to 0.45.0

Bump policyengine-canada to 0.45.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.277.0

Bump policyengine-us to 0.277.0

---

changelog_entry.yaml
setup.py

Bump policyengine-us to 0.278.0

Bump policyengine-us to 0.278.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine us to 0.280.0

Update PolicyEngine us to 0.280.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine us to 0.281.0

Update PolicyEngine us to 0.281.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine us to 0.282.0

Update PolicyEngine us to 0.282.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine us to 0.285.0

Update PolicyEngine us to 0.285.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine us to 0.285.1

Update PolicyEngine us to 0.285.1

---

changelog_entry.yaml
policyengine_api/country.py
policyengine_api/endpoints/household.py

Fix zeroed out household values

---

changelog_entry.yaml
setup.py

Update PolicyEngine us to 0.286.0

Update PolicyEngine us to 0.286.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine us to 0.286.2

Update PolicyEngine us to 0.286.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine uk to 0.45.1

Update PolicyEngine uk to 0.45.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine us to 0.294.0

Update PolicyEngine us to 0.294.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine us to 0.295.0

Update PolicyEngine us to 0.295.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine canada to 0.46.0

Update PolicyEngine canada to 0.46.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine canada to 0.47.0

Update PolicyEngine canada to 0.47.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine us to 0.295.1

Update PolicyEngine us to 0.295.1

---

changelog_entry.yaml
gcp/bump_country_package.py
policyengine_api/endpoints/economy/economy.py
policyengine_api/endpoints/economy/reform_impact.py
setup.py

Update PolicyEngine us to 0.296.0

Update PolicyEngine us to 0.296.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.297.0

Update PolicyEngine US to 0.297.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.298.0

Update PolicyEngine US to 0.298.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.299.0

Update PolicyEngine US to 0.299.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.47.1

Update PolicyEngine CANADA to 0.47.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.46.0

Update PolicyEngine UK to 0.46.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.48.0

Update PolicyEngine UK to 0.48.0

---

changelog_entry.yaml
policyengine_api/country.py
policyengine_api/endpoints/economy/single_economy.py

Add NYC economic impact option

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.301.2

Update PolicyEngine US to 0.301.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.302.0

Update PolicyEngine US to 0.302.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.303.0

Update PolicyEngine US to 0.303.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.49.0

Update PolicyEngine CANADA to 0.49.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.307.0

Update PolicyEngine US to 0.307.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.50.0

Update PolicyEngine CANADA to 0.50.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.52.0

Update PolicyEngine CANADA to 0.52.0

---

changelog_entry.yaml
policyengine_api/endpoints/household.py

@MaxGhenis  this might be the underlying cause of the household-related issues you filed, will see

Handle errors more reliably

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.310.0

Update PolicyEngine US to 0.310.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.310.1

Update PolicyEngine US to 0.310.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.54.0

Update PolicyEngine CANADA to 0.54.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.311.0

Update PolicyEngine US to 0.311.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.313.0

Update PolicyEngine US to 0.313.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.314.0

Update PolicyEngine US to 0.314.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.314.1

Update PolicyEngine US to 0.314.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.56.0

Update PolicyEngine CANADA to 0.56.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.58.0

Update PolicyEngine CANADA to 0.58.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.316.0

Update PolicyEngine US to 0.316.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.316.1

Update PolicyEngine US to 0.316.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.317.0

Update PolicyEngine US to 0.317.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.59.0

Update PolicyEngine CANADA to 0.59.0

---

README.md
changelog_entry.yaml
policyengine_api/country.py

cc @MaxGhenis I think this caused https://github.com/PolicyEngine/policyengine-app/issues/531

Add error safety check

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.60.0

Update PolicyEngine CANADA to 0.60.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.318.0

Update PolicyEngine US to 0.318.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.319.0

Update PolicyEngine US to 0.319.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.320.0

Update PolicyEngine US to 0.320.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.61.0

Update PolicyEngine CANADA to 0.61.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.320.1

Update PolicyEngine US to 0.320.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.49.1

Update PolicyEngine UK to 0.49.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.321.0

Update PolicyEngine US to 0.321.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.62.0

Update PolicyEngine CANADA to 0.62.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.329.0

Update PolicyEngine US to 0.329.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.329.1

Update PolicyEngine US to 0.329.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.64.0

Update PolicyEngine CANADA to 0.64.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.50.1

Update PolicyEngine UK to 0.50.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.329.2
Fixes #470

 Fixes #470 Update PolicyEngine US to 0.329.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.65.0

Update PolicyEngine CANADA to 0.65.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.329.3

Update PolicyEngine US to 0.329.3

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.330.1

Update PolicyEngine US to 0.330.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.331.0

Update PolicyEngine US to 0.331.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.67.0

Update PolicyEngine CANADA to 0.67.0

---

changelog_entry.yaml
policyengine_api/data/data.py
policyengine_api/endpoints/analysis.py
policyengine_api/endpoints/economy/economy.py
policyengine_api/endpoints/economy/reform_impact.py
policyengine_api/endpoints/household.py
policyengine_api/endpoints/policy.py

Fix local debugging issues

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.334.0

Update PolicyEngine US to 0.334.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.335.0

Update PolicyEngine US to 0.335.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.51.0

Update PolicyEngine UK to 0.51.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.335.1

Update PolicyEngine US to 0.335.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.51.1

Update PolicyEngine UK to 0.51.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.337.1

Update PolicyEngine US to 0.337.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.338.0

Update PolicyEngine US to 0.338.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.339.1

Update PolicyEngine US to 0.339.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.340.0

Update PolicyEngine US to 0.340.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.341.0

Update PolicyEngine US to 0.341.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.342.0

Update PolicyEngine US to 0.342.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.345.0

Update PolicyEngine US to 0.345.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.345.1

Update PolicyEngine US to 0.345.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.68.0

Update PolicyEngine CANADA to 0.68.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.345.12

Update PolicyEngine US to 0.345.12

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.346.0

Update PolicyEngine US to 0.346.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.346.2

Update PolicyEngine US to 0.346.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.348.0

Update PolicyEngine US to 0.348.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.69.0

Update PolicyEngine CANADA to 0.69.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.350.0

Update PolicyEngine US to 0.350.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.350.1

Update PolicyEngine US to 0.350.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.352.0

Update PolicyEngine US to 0.352.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.353.0

Update PolicyEngine US to 0.353.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.354.0

Update PolicyEngine US to 0.354.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.357.0

Update PolicyEngine US to 0.357.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.357.1

Update PolicyEngine US to 0.357.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.358.0

Update PolicyEngine US to 0.358.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.52.0

Update PolicyEngine UK to 0.52.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.359.0

Update PolicyEngine US to 0.359.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.359.1

Update PolicyEngine US to 0.359.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.360.0

Update PolicyEngine US to 0.360.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.360.1

Update PolicyEngine US to 0.360.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.362.0

Update PolicyEngine US to 0.362.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.363.0

Update PolicyEngine US to 0.363.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.364.1

Update PolicyEngine US to 0.364.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.365.0

Update PolicyEngine US to 0.365.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.366.0

Update PolicyEngine US to 0.366.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.367.0

Update PolicyEngine US to 0.367.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.53.0

Update PolicyEngine UK to 0.53.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.369.0

Update PolicyEngine US to 0.369.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.370.0

Update PolicyEngine US to 0.370.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.370.1

Update PolicyEngine US to 0.370.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.371.0

Update PolicyEngine US to 0.371.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.70.0

Update PolicyEngine CANADA to 0.70.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.373.0

Update PolicyEngine US to 0.373.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.377.1

Update PolicyEngine US to 0.377.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.379.0

Update PolicyEngine US to 0.379.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.380.0

Update PolicyEngine US to 0.380.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.386.0

Update PolicyEngine US to 0.386.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.387.1

Update PolicyEngine US to 0.387.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.54.0

Update PolicyEngine UK to 0.54.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.388.0

Update PolicyEngine US to 0.388.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.389.1

Update PolicyEngine US to 0.389.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.393.0

Update PolicyEngine US to 0.393.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.394.0

Update PolicyEngine US to 0.394.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.396.0

Update PolicyEngine US to 0.396.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.397.0

Update PolicyEngine US to 0.397.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.400.0

Update PolicyEngine US to 0.400.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.401.0

Update PolicyEngine US to 0.401.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.401.1

Update PolicyEngine US to 0.401.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.401.2

Update PolicyEngine US to 0.401.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.401.5

Update PolicyEngine US to 0.401.5

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.402.0

Update PolicyEngine US to 0.402.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.403.0

Update PolicyEngine US to 0.403.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.403.1

Update PolicyEngine US to 0.403.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.403.2

Update PolicyEngine US to 0.403.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.403.3

Update PolicyEngine US to 0.403.3

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.405.0

Update PolicyEngine US to 0.405.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.407.0

Update PolicyEngine US to 0.407.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.408.0

Update PolicyEngine US to 0.408.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.409.0

Update PolicyEngine US to 0.409.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.409.1

Update PolicyEngine US to 0.409.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.409.2

Update PolicyEngine US to 0.409.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.409.3

Update PolicyEngine US to 0.409.3

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.410.0

Update PolicyEngine US to 0.410.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.71.0

Update PolicyEngine CANADA to 0.71.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.410.1

Update PolicyEngine US to 0.410.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.410.2

Update PolicyEngine US to 0.410.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.411.0

Update PolicyEngine US to 0.411.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.415.0

Update PolicyEngine US to 0.415.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.72.0

Update PolicyEngine CANADA to 0.72.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.416.0

Update PolicyEngine US to 0.416.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.416.1

Update PolicyEngine US to 0.416.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.416.2

Update PolicyEngine US to 0.416.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.417.0

Update PolicyEngine US to 0.417.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.417.1

Update PolicyEngine US to 0.417.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.417.3

Update PolicyEngine US to 0.417.3

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.73.0

Update PolicyEngine CANADA to 0.73.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.419.0

Update PolicyEngine US to 0.419.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.74.0

Update PolicyEngine CANADA to 0.74.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.422.0

Update PolicyEngine US to 0.422.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.76.0

Update PolicyEngine CANADA to 0.76.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.423.0

Update PolicyEngine US to 0.423.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.55.1

Update PolicyEngine UK to 0.55.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.423.1

Update PolicyEngine US to 0.423.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.424.0

Update PolicyEngine US to 0.424.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.424.1

Update PolicyEngine US to 0.424.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.425.1

Update PolicyEngine US to 0.425.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.79.0

Update PolicyEngine CANADA to 0.79.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.427.0

Update PolicyEngine US to 0.427.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.428.0

Update PolicyEngine US to 0.428.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.429.1

Update PolicyEngine US to 0.429.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.430.0

Update PolicyEngine US to 0.430.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.431.1

Update PolicyEngine US to 0.431.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.431.2

Update PolicyEngine US to 0.431.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.431.3

Update PolicyEngine US to 0.431.3

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.432.0

Update PolicyEngine US to 0.432.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.80.0

Update PolicyEngine CANADA to 0.80.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.436.0

Update PolicyEngine US to 0.436.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.437.0

Update PolicyEngine US to 0.437.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.80.1

Update PolicyEngine CANADA to 0.80.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.80.2

Update PolicyEngine CANADA to 0.80.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.438.0

Update PolicyEngine US to 0.438.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.439.0

Update PolicyEngine US to 0.439.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.439.1

Update PolicyEngine US to 0.439.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.55.2

Update PolicyEngine UK to 0.55.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.441.0

Update PolicyEngine US to 0.441.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.81.0

Update PolicyEngine CANADA to 0.81.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.442.0

Update PolicyEngine US to 0.442.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.82.0

Update PolicyEngine CANADA to 0.82.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.443.0

Update PolicyEngine US to 0.443.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.445.0

Update PolicyEngine US to 0.445.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.447.0

Update PolicyEngine US to 0.447.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.447.1

Update PolicyEngine US to 0.447.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.449.0

Update PolicyEngine US to 0.449.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.450.0

Update PolicyEngine US to 0.450.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.451.0

Update PolicyEngine US to 0.451.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.452.0

Update PolicyEngine US to 0.452.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.452.1

Update PolicyEngine US to 0.452.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.453.0

Update PolicyEngine US to 0.453.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.454.0

Update PolicyEngine US to 0.454.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.455.0

Update PolicyEngine US to 0.455.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.456.0

Update PolicyEngine US to 0.456.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.458.0

Update PolicyEngine US to 0.458.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.458.2

Update PolicyEngine US to 0.458.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.83.0

Update PolicyEngine CANADA to 0.83.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.460.1

Update PolicyEngine US to 0.460.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.462.1

Update PolicyEngine US to 0.462.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.462.2

Update PolicyEngine US to 0.462.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.462.3

Update PolicyEngine US to 0.462.3

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.463.0

Update PolicyEngine US to 0.463.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.465.0

Update PolicyEngine US to 0.465.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.471.1

Update PolicyEngine US to 0.471.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.474.0

Update PolicyEngine US to 0.474.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.84.0

Update PolicyEngine CANADA to 0.84.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.476.0

Update PolicyEngine US to 0.476.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.479.0

Update PolicyEngine US to 0.479.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.481.0

Update PolicyEngine US to 0.481.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.482.1

Update PolicyEngine US to 0.482.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.483.0

Update PolicyEngine US to 0.483.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.85.0

Update PolicyEngine CANADA to 0.85.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.484.0

Update PolicyEngine US to 0.484.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.485.0

Update PolicyEngine US to 0.485.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.486.0

Update PolicyEngine US to 0.486.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.488.0

Update PolicyEngine US to 0.488.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.488.1

Update PolicyEngine US to 0.488.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.491.0

Update PolicyEngine US to 0.491.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.492.0

Update PolicyEngine US to 0.492.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.493.0

Update PolicyEngine US to 0.493.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.86.0

Update PolicyEngine CANADA to 0.86.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.86.1

Update PolicyEngine CANADA to 0.86.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.86.2

Update PolicyEngine CANADA to 0.86.2
