changelog_entry.yaml
policyengine_api/api.py
policyengine_api/compute_api/compute_api.py
tests/compute_api/test_uk_baseline_policy.yaml

RIght now the compute API server creates a new thread for every population impact calculation. [But that thread might be being silently terminated by GCP.](https://stackoverflow.com/questions/68017313/can-i-use-background-threads-on-google-app-engine-standard-python-3)
So this attempts to circumvent that by running all population impact routines in the thread they're already in (that GCP created). The thinking is that GCP probably wouldn't kill a GCP-started thread.

Fix population impacts issue (hopefully)

---

changelog_entry.yaml
policyengine_api/api.py
policyengine_api/endpoints/computed_household.py

The /calculate endpoint currently tries to cache households, but I think the speed of the OpenFisca simulation means that the database calls are actually the limiting factor on speed. So here I've tweaked it to ensure no database calls are made. On my Mac this cuts the runtime of /us/calculate (on SNAP) from 1.5s to 0.3s on average.
cc @MaxGhenis

Cut /calculate runtime by around 70%

---

dashboard/experiments/gpt4_api_user.py

Leaving out changelog information because this doesn't need a version update

Add Streamlit app for GPT4 analysis

---

CHANGELOG.md
changelog.yaml
changelog_entry.yaml
gcp/Dockerfile
policyengine_api/constants.py
policyengine_api/setup_data.py
policyengine_api/worker.py
setup.py

Workers previously didn't import the package before running jobs, which meant every impact job had ~9 seconds of import time repeated. This PR fixes that.

Optimise economic impact workers

---

.github/workflows/pr.yml
.github/workflows/push.yml
changelog_entry.yaml

Upgrades `actions/checkout`, utilized in GitHub actions, from v2 to v3, as described in #228. Only breaking change appears to be that `actions/checkout` upgraded from Node 12 to Node 16.

Upgrade GitHub actions/checkout from v2 to v3

---

changelog_entry.yaml
policyengine_api/data/data.py

Added code to `/data/data.py` to check for whether or not app is in debug mode, then alter remote db connection based upon this. I'm not sure if this is Python best practice, I'm merely mimicking a practice in Node. However, this code would enable local deployment and execution of pytest without having to manually change `/data/data.py`. Fixes #439.

Check for debug mode before initializing remote db

---

Makefile
changelog_entry.yaml

Adds `make debug-test` script to Makefile to allow for local Pytest execution without altering `make test` or having to manually change database connections in `/data/data.py`. Fixes #476.

Add debug-test script to Makefile to allow for local testing

---

changelog_entry.yaml
policyengine_api/api.py
policyengine_api/utils/__init__.py
policyengine_api/utils/cache_utils.py
setup.py
tests/python/data/calculate_us_1_data.json
tests/python/data/calculate_us_2_data.json
tests/python/test_calculate_us_1.py

Added Flask-Caching (https://flask-caching.readthedocs.io/en/latest/) experimentally for `/calculate`.
- ~~To test it you'd need `pip install Flask-Caching`, I didn't see a requirements.txt at first glance, not sure how to add as dep now, I'll fix it.~~
~~Did a few tests (about 3 clicks) and it looks promising. I'll continue to do some tests next week.~~

Setup Flask-Caching for /calculate endpoint.

---

changelog_entry.yaml
policyengine_api/api.py

PR #495 mistakenly added caching for `/economy`.
There was already a different kind of caching for this endpoint that works fine.
The added cache, caches the "calculating" response and answers that for any future requests thus the calculation results never get answered.

[URGENT] Bugfix: remove caching for /economy

---

changelog_entry.yaml
tests/python/data/calculate_us_1_data.json
tests/python/data/calculate_us_2_data.json

Rename `nj_child_tax_credit` to `nj_ctc` in tests

---

changelog_entry.yaml
policyengine_api/endpoints/household.py

Add `ETERNITY` and `MONTH`-level variables to households

---

changelog_entry.yaml
policyengine_api/endpoints/household.py

Fixes #1030. This PR removes hard-coding of annual values in the `add_yearly_variables` function by first determining what year is utilized in the emitted household object, then populating all default variables utilizing that year. A video demonstrating the changes working properly is available [here](https://www.loom.com/share/bfacee18167d4520a52c1137ec262cab?sid=fe6772e4-edb3-48ad-989b-d9af6dc5a07f), where household #100013 is a pre-created default US household with 0 income that's emitted to the local test database before making this video.
This code must be added successfully before proceeding with https://github.com/PolicyEngine/policyengine-app/issues/1017

Remove annual hardcoding from API

---

changelog_entry.yaml
policyengine_api/country.py

Fixes #1097. Is a prerequisite for app [#1208](https://github.com/PolicyEngine/policyengine-app/issues/1208). This commit adds 2025 as a year for the API's US country setup.
In a Loom video [here](https://www.loom.com/share/7501bc0a6e894f21bb22ee25629c67c1?sid=440131f8-a5b6-4605-8b4f-bf87eb641eba), I test this running locally by creating two identical household objects for 2024 and 2025, then POSTing to the household creation endpoint for each. I then take each household ID and GET them over current law, demonstrating that the returned household net income of each is the same. Finally, I show the locally running API logs, showing no issue. Note that the error logs regarding California tax variables visible in the video are from when I ran tests over 2023, when those variables did not …

Enable 2025 household calculations for US

---

changelog_entry.yaml
gcp/policyengine_api/app.yaml

Fixes #1034. This commit reduces the number of CPUs available to the app to the minimum possible while still maintaining the amount of RAM the deployment is permitted, per the formula available at https://cloud.google.com/appengine/docs/flexible/reference/app-yaml?tab=python#resource-settings, in an effort to reduce unnecessary resource consumption.

Alter CPU deployment

---

changelog_entry.yaml
policyengine_api/endpoints/household.py

Fixes #1067. This PR ensures that `get_household_year` doesn't break if the head of household possesses an `age` variable, but this variable is empty. Though it is a bug, this situation emerged at times recently due to a front-end design oversight (age was added by default to all household members except head of household) and a bug (pre-seeding of variables within the `VariableEditor` component only added variables if they didn't exist in any household member, meaning that when `age` was the variable within the component, it was impossible to add it for head of household). 
Though the fixes to these bugs have either been fixed or are in review in `policyengine-app`, it would be best to account for this potential circumstance in the back end to at least allow for more graceful failure.

Ensure get_household_year doesn't break on empty age variable

---

Makefile
changelog_entry.yaml

Fixes #1349. Should be removed once deployment issues are diagnosed and fixed.

Remove capturing so as to get fuller datastream during tests

---

changelog_entry.yaml
policyengine_api/country.py
tests/python/test_units.py

- We fix #1195 by calling the method `propagate_units` in `build_parameters`, which propagates units correctly to descendants of `ParameterScale` objects. `propagate_units` was added to `ParameterScale` objects in https://github.com/PolicyEngine/policyengine-core/pull/162.
- We add a test to check that the units are propagated correctly.

Propagate units to descendants for ParameterScale objects

---

changelog_entry.yaml
policyengine_api/country.py

Fixes #1364 
This removes the 2021 option in the US country metadata, which is contained in the file "country.py".

Remove 2021 option in US metadata

---

.gitignore
changelog_entry.yaml
policyengine_api/api.py
policyengine_api/data/data.py
policyengine_api/data/initialise.sql
policyengine_api/data/initialise_local.sql
policyengine_api/endpoints/__init__.py
policyengine_api/endpoints/policy.py
tests/python/test_policy.py
tests/python/test_user_policy.py

Fixes #1381 
Fixes #1382 
Fixes #1383 
This PR creates a new table, `user_policies`, that stores instances of policies created by authenticated users, storing their user ID. This then creates a GET route that returns an array of all policies a user with a particular ID has created, as well as a POST route for creating individual user-policy associations. This is a prerequisite for solving various front-end issues aimed at creating an authenticated user experience.

Create user policy table

---

changelog_entry.yaml
policyengine_api/endpoints/policy.py
tests/python/test_user_policy.py

Fixes #1404. This PR ensures that any time a user policy is emitted to the database, a new record is only created if unique (barring the "type" field, which it does not check at the moment). Below is a video demonstrating the behavior when records are emitted to the testing database with Postman. This also adds a test to ensure proper behavior.
https://github.com/PolicyEngine/policyengine-api/assets/14987227/7aaf74cc-0207-4826-94c1-ce7161cafb24

Ensure unique user policies

---

changelog_entry.yaml
policyengine_api/api.py
policyengine_api/data/initialise.sql
policyengine_api/data/initialise_local.sql
policyengine_api/endpoints/__init__.py
policyengine_api/endpoints/policy.py
policyengine_api/endpoints/user_profile.py
tests/python/test_user_policy.py
tests/python/test_user_profile.py

Fixes #1407. 
Fixes #1410.
Fixes #1411.
Fixes #1412.
Fixes #1417.
Fixes #1418.
Fixes #1420.
This PR adds created_date, updated_date, year, geography, number_of_provisions, budgetary_cost, and api_version as required columns (except budgetary_cost, which is optional) to the user_policy table, and updates `set_user_policy`, `get_user_policy`, and the user_policy table's Pytest test to handle these additions. It also changes the response status of a POST request where a user record already exists to "ok". It creates a PUT endpoint to enable modifications of existing records using the record ID that is returned by the POST controller if the record already exists, enabling both the updating of the `updated_date` and `api_version` fields of an existing record, as well as the addition of a …

Add items to user_policy table

---

changelog_entry.yaml
policyengine_api/data/initialise.sql
policyengine_api/data/initialise_local.sql
policyengine_api/endpoints/user_profile.py
tests/python/test_user_policy.py
tests/python/test_user_profile.py

Fixes #1425. 
Fixes #1427.
First, this PR changes the timestamp values from the `user_profiles` and `user_policies` tables to BIGINT types, since they will be consumed by the front end in the context of JavaScript's `Date.now()` function, which returns the number of seconds since the epoch. This also prevents the numerous Python-JS-SQLite-MySQL conflicts that have emerged in the context of the DATETIME type (Python has various different formats, JS's formats are all based on epoch time, SQLite has no native handling and converts everything to TEXT using specialized handlers, and MySQL requires very specific formatting for successful insertion).
Additionally, instead of merely returning the created `user_id` value, this PR enables the `user_profile` POST endpoint to return the entire user …

user_profile POST requests now return complete user object

---

changelog_entry.yaml
policyengine_api/endpoints/policy.py

Fixes #1439. After creating a `user_policy` record in the `user_policies` table via the `set_user_policy` endpoint, this PR returns the entire new record by running a subsequent SELECT call to the `user_policies` table. This will enable the front end to pass the created ID value to the app, allowing for subsequent PUT requests to update elements of the policy.

Return created user_policy id

---

changelog_entry.yaml
policyengine_api/endpoints/policy.py

Fixes #1436. Previously, the `get_user_policy` endpoint only fetched policies corresponding to the current country ID, but due to a change in thinking surrounding how user profiles should work, this now fetches all policies created by the user.

Fetch all user policies, not just those corresponding with current country

---

changelog_entry.yaml
policyengine_api/endpoints/policy.py
tests/python/test_user_policy.py

Fixes #1441. This PR ensures that for the SELECT statement utilized by the `set_user_policy` endpoint, items with a value of `None` are converted to a SQL `NULL`.

In user_policy table, convert None values to IS NULL within SELECT statements

---

changelog_entry.yaml
tests/python/test_user_policy.py

Fixes #1455. In the previous iteration of this test, the test failed to properly delete the existing test record, then failed to clean itself up by deleting the test record it creates, and this PR fixes both of those shortcomings.

Fix test_nulls test to properly delete existing record

---

changelog_entry.yaml
policyengine_api/endpoints/policy.py

Fixes #1462. This functionally reverts #1438 in order to restrict the user policies returned by the `user_policy` GET endpoint to those of the country_id passed via the URL, preventing a challenging front-end bug whereby displaying all of a user's policies across countries fails because the front-end app has no access to the relevant metadata for other countries.

Change get_user_policy controller to filter by country_id

---

changelog_entry.yaml
policyengine_api/endpoints/policy.py

Fixes #1459. This ensures that `budgetary_impact` isn't treated as a unique key within a record, preventing duplicate record creation when a user accesses their profile.

Remove `budgetary_impact` from the `set_user_policy` endpoint's unique record testing

---

changelog_entry.yaml
gcp/policyengine_api/start.sh
policyengine_api/endpoints/analysis.py

Fixes #1510.
Currently, the API's `get_analysis` endpoint passes a single argument into the `PolicyEngineDatabase.query()` statement that runs on the deployed database. However, this argument is a string, while the deployed database calls for a list and the local database that runs alongside it (and which we use to debug) calls for a tuple.
I'm not entirely sure why this wasn't a problem with our prior ChatGPT implementation, but I have a few theories that I won't expound on here. Either way, it seems to be a bigger issue with the deployed MySQL database than the local SQLite one, so the below video demonstrates the code working with the deployed database:
https://github.com/PolicyEngine/policyengine-api/assets/14987227/02fa0de3-460b-4243-b927-1e112559e699

Repair `get_analysis` endpoint

---

changelog_entry.yaml
policyengine_api/endpoints/economy/single_economy.py

Fixes #1545
We should fix this in PolicyEngine-US, but essentially: sometimes we get -1 decile values for a few individual records. Probably because of negative income. But then when all records in one decile have zero weight, we get an error when taking the mean of something grouped by decile.

Fix DC microsims fail in web app

---

changelog_entry.yaml
policyengine_api/endpoints/economy/compare.py

Fixes #1539. This PR adds calculation of overall relative labor supply response impacts to the relevant controller in a similar fashion to #1547. This is a requirement for https://github.com/PolicyEngine/policyengine-app/issues/1787. This PR does not add any relevant tests, but if desired, that can be done.

Add overall relative LSR impacts

---

changelog_entry.yaml
policyengine_api/endpoints/economy/economy.py

Fixes #1578. This PR adds a separate `queue_position` element to the output in cases where the API is in the process of calculating and ensures that both display the queue position as "0" instead of "None" when an item is being actively calculated.
This is necessary to fix https://github.com/PolicyEngine/policyengine-app/issues/1883.

Change how queue positioning is reported

---

.github/workflows/pr.yml
.github/workflows/push.yml
changelog_entry.yaml
gcp/Dockerfile
gcp/policyengine_api/start.sh
setup.py

Fixes #1437.
Fixes #438.
Updates GCP install to Python 3.10 and pins various packages that hinder local development/execution.

Update API, GCP to Python 3.10

---

.github/workflows/pr.yml
.github/workflows/push.yml
changelog_entry.yaml
docker/Dockerfile
gcp/Dockerfile
gcp/README.md
gcp/policyengine_api/app.yaml
gcp/policyengine_api/start.sh
setup.py

Fixes #1634 
Fixes #1635 
PR changes how we deploy from a Docker container, using the Docker version of Python 3.10 instead of a custom-built one to avoid issues with the `_ssl` module, as even when manually installing relevant versions of OpenSSL, the module simply wouldn't build.

Fix Docker settings

---

changelog_entry.yaml
gcp/policyengine_api/Dockerfile

Fixes #1639.
PR updates the `push` GitHub Action to pull the Docker image, from which we launch, from the newer `policyengine` account instead of the older `nikhilwoodruff` one.

Update Dockerfile pull address

---

changelog_entry.yaml
gcp/policyengine_api/Dockerfile

Fixes #1641.
This PR adds the changes recommended by Claude to the GCP launch Dockerfile to (hopefully) get the `start.sh` file to run properly.

Use recommended changes to Dockerfile

---

changelog_entry.yaml
gcp/policyengine_api/app.yaml

ISSUE TO BE ADDED. This is a draft PR that would increase the max number of GCP instances to 2.

Increase max GCP instances to 2

---

changelog_entry.yaml
policyengine_api/endpoints/economy/compare.py
policyengine_api/endpoints/economy/single_economy.py

Fixes #1603. This PR changes where the `decile_impact` and `wealth_decile_impact` functions filter out households with negative household net incomes. These households appear to only exist as a result of the `enhanced_cps` dataset, and the households with the lowest negative incomes have such incredibly negative incomes that they skew the relative decile impact to be negative. 
Instead of doing so after grouping households by decile, this PR removes these households beforehand.
Before pushing, a visual demonstration of the new outputs in the front-end app will be added.
Prior to approval, I'd like to confirm that this approach is technically feasible, as I'm unsure if this method will result in an uneven decile distribution after filtering out households with negative net incomes.

Filter households with negative incomes out of `decile_impact` and `wealth_decile_impact` prior to applying formulas

---

README.md
changelog_entry.yaml

Updated README for getting test environment up

---

changelog_entry.yaml
policyengine_api/endpoints/economy/economy.py

Fixes #1580
- Removed queue message

Fix Removed queue message

---

changelog_entry.yaml
policyengine_api/endpoints/tracer_analysis.py

Fixes #1864. I'm unable to reproduce the issue behind #1864 locally, so I'm hoping that this will fix the issue.

Explicitly return stream with context within response object

---

changelog_entry.yaml
policyengine_api/endpoints/policy.py

- Added checks for when no policy is found in `get_policy_search`

Fix `get_policy_search` endpoint to return `404` when no policy is found

---

changelog_entry.yaml
policyengine_api/utils/json.py

Fixes #1866.
Fixes #1886.
This changes the string value that infinite values are set to, allowing for more logical processing on the front end. This change is very minimal, hence I feel no tests are needed in this case.
This must be merged before the accompanying front-end changes in https://github.com/PolicyEngine/policyengine-app/pull/2103.

Handle JS Infinity

---

.github/workflows/pr.yml
.github/workflows/push.yml
changelog_entry.yaml
docker/Dockerfile
gcp/Dockerfile
gcp/policyengine_api/start.sh

Fixes #1924
@tawandamoyo This re-enables Python 3.11 by removing the explicit call to run from Python 3.11, as the Docker dependencies that this runs off were previously installed using Python 3.10.

Re-enable Python 3.11, remove explicity version call in start.sh

---

changelog_entry.yaml
policyengine_api/endpoints/economy/single_economy.py

Remove chunking

---

.gitignore
changelog_entry.yaml
policyengine_api/api.py

The flask app defines the same GET operation on /simulations twice. This change simply removes one of them.

Remove duplicate route for /simulations (#1952)

---

changelog_entry.yaml
gcp/policyengine_api/app.yaml
policyengine_api/api.py
policyengine_api/openapi_spec.yaml
tests/api/test_liveness.yaml
tests/api/test_readiness.yaml
tests/python/test_user_policy.py
tests/python/test_user_profile.py

Rename endpoints to use hyphens not underscores

---

changelog_entry.yaml
gcp/policyengine_api/start.sh

Fixes #1963.
Ensures that `gcp/start.sh` works with standard shell utilities, instead of Bash-specific ones.

Fix start.sh

---

changelog_entry.yaml
policyengine_api/country.py
policyengine_api/endpoints/household.py
policyengine_api/endpoints/policy.py
policyengine_api/endpoints/simulation_analysis.py

This PR contains some drive-by cleanup changes that should not impact functionality.
- Removes unused imports from files in the `policyengine_api/endpoints` directory
- Removes empty file `policyengine_api/endpoints/analysis.py`
- Removes unused copy of results list in`policyengine_api/endpoints/policy.py`

[Minor] Clean up unused imports & files

---

changelog_entry.yaml
policyengine_api/endpoints/household.py
policyengine_api/endpoints/metadata.py
policyengine_api/endpoints/policy.py
policyengine_api/endpoints/tracer_analysis.py
policyengine_api/endpoints/user_profile.py
policyengine_api/helpers/validate_country.py
policyengine_api/routes/economy_routes.py
tests/python/test_country.py
tests/python/test_policy.py
tests/python/test_validate_country.py

Currently, there is a repeated check and short-circuit in many functions to validate existence of the given country ID. This PR refactors `validate_country` as a decorator to DRY the code. We may consider transitioning this to a `before_request` hook to further reduce code repetition.
This is essentially a refactor. There should be no functional change.
- Update `validate_country` to change it into a decorator/wrapper
- Replace instances of `validate_country()` check & short circuit -> `@validate_country` decorator
- Add unit tests for the `validate_country` function
- Add a sanity test in `test_policy.py` to ensure that the decorator functionality works

Switch @validate_country to decorator

---

changelog_entry.yaml
policyengine_api/routes/metadata_routes.py

Fixes #PolicyEngine/issues#30
This issue was created by an improper assumption in #2038 whereby the metadata endpoint was improperly documented, and changes based upon the typing documentation created a doubly nested output that does not fit our intended schema. This reverts that, and a future issue will be opened to properly configure this so that the metadata route and service are configured as expected.

Remove improperly netsted metadata JSON

---

changelog_entry.yaml
policyengine_api/data/data.py

Fixes #1362 
* What: Removed the definition for _seed_ method from _PolicyEngineDatabase_ class as well as any calls to the method from within the class.
* Why:  Test code that is no longer required.

Removed seed method from PolicyEngineDatabase class

---

changelog_entry.yaml
policyengine_api/jobs/calculate_economy_simulation_job.py

Point the API to HuggingFace datasets

---

.github/workflows/pr.yml
.github/workflows/push.yml
changelog_entry.yaml

Fixes [#998 ](https://github.com/PolicyEngine/policyengine-api/issues/998) and [#997 ](https://github.com/PolicyEngine/policyengine-api/issues/997). Upgrade checkout action from v3 to v4 & Upgrade setup-gcloud from v1 to v2

Upgrade checkout action from v3 to v4 & Upgrade setup-gcloud from v1 to v2 

---

changelog_entry.yaml
policyengine_api/endpoints/economy/compare.py

Fixes #2167.
In the code for the "Winners and losers" chart, in situations where the number of individuals in a decile is 0 (due to a potential bug in `microdf`), this code calculates the number of people within a given affect group (e.g., "Gain by more than 5%") as 0. This does create minor visual disparities on the front end, but allows the baseline and reform comparison code to complete properly, enabling use of the tool outside of the decile impacts.
The below video demonstrates these visual issues with a local reproduction of the DC-based policy listed in #2164.
[AwesomeScreenshot-2_13_2025,12_11_36AM.webm](https://github.com/user-attachments/assets/1fdbc51a-01d4-4202-b399-5017ad28cc5b)

Temporarily patch issues with decile outputs in state-level ECPS runs

---

changelog_entry.yaml
policyengine_api/country.py
policyengine_api/endpoints/economy/compare.py
policyengine_api/jobs/calculate_economy_simulation_job.py

Add UK Parliamentary constituency estimates

---

changelog_entry.yaml
policyengine_api/endpoints/economy/compare.py

Return the Parliamentary constituency data in dictionary form

---

changelog_entry.yaml
policyengine_api/ai_prompts/simulation_analysis_prompt.py
policyengine_api/endpoints/economy/compare.py

Fixes #2213 
In the interest of time, this PR does as little as necessary to fix this output. An improvement would be to fix #2214, which this PR does not do in favor of fixing it within API v2.
This PR allows for the UK constituency breakdown segment of a baseline-reform pair's economic impacts analysis to be `None`, which would be the case for the US.
Here's a video of the changes with a locally running version of the app on top:
[AwesomeScreenshot-2_25_2025,8_09_22PM.webm](https://github.com/user-attachments/assets/3db44614-d22c-49a2-8e32-d1405fd44f3b)

Enable simulation impacts for US

---

.github/workflows/push.yml
changelog_entry.yaml

Remove env var tests from deploy

---

changelog_entry.yaml
policyengine_api/country.py
policyengine_api/endpoints/economy/compare.py
policyengine_api/jobs/calculate_economy_simulation_job.py
tests/unit/fixtures/jobs/test_calculate_economy_simulation_job.py

Fixes #2210
This cannot be merged until `parliamentary_constituency_weights.h5` is successfully uploaded to the `policyengine/policyengine-uk-data-public` model on Hugging Face; it will remain in draft until that is complete.
For basic, public-access data files, this PR uses a new publicly available Hugging Face model to enable users to still run the package and run tests.

Use new public Hugging Face model

---

changelog_entry.yaml
policyengine_api/services/tracer_analysis_service.py
tests/fixtures/services/tracer_analysis_service.py
tests/unit/services/test_tracer_analysis_service.py

Fixes #2290
- Modified the `tracer_analysis_service._parse_tracer_output`  method to fix the empty tracer bug. 
- Bug was caused due to incorrect regex pattern matching and valid tracer segments getting skipped. This pattern was change was introduced during #2181  - for certain test case failures.
- These failing tests (Empty input target variable and target variable thats substring of other variable) are now removed from the test module and regex pattern is reverted to original. In future, the pattern could be fixed to work for these test cases.

Bug fix for tracer_analysis_service.parse_tracer_output - empty tracer being returned

---

changelog_entry.yaml
gcp/policyengine_api/app.yaml

Fixes #2327 
Fixes #2328 
Corrects the path used by Google during deployment to ping readiness checks and lowers the failure timeout for said checks back to 400s

Correct readiness check path, lower timeout back to 400s

---

changelog_entry.yaml
policyengine_api/jobs/calculate_economy_simulation_job.py

Fix APIv2 comparison to allow zero = 1e-5

---

Makefile
changelog_entry.yaml

Fixes #2370
Extends Google Cloud build timeout to 40 minutes

Extend Google Cloud build timeout to 40 minutes

---

changelog_entry.yaml
policyengine_api/services/tracer_analysis_service.py
tests/fixtures/services/tracer_analysis_service.py
tests/unit/services/test_tracer_analysis_service.py

fixes #2304
Fix tracer parsing function to properly handle variables whose names are substrings of other variables

Fix tracer parsing function to properly handle variables

---

.github/workflows/push.yml
changelog_entry.yaml

Fixes #2423
Running multiple deploys concurrently will result in race conditions. We believe this is currently causing the gcloud app deploy command to be confused about which previous version or versions to stop, but it could cause other issues as well.
This change uses a concurrency group to only permit a single deploy to execute at a time.

Prevent concurrent deploys.

---

changelog_entry.yaml
policyengine_api/jobs/calculate_economy_simulation_job.py
policyengine_api/services/policy_service.py
tests/fixtures/jobs/test_calculate_economy_simulation_job.py
tests/unit/jobs/test_calculate_economy_simulation_job.py

Fixes #2445 
This code refactors how we handle simulation API job setup. It creates methods specific to converting API v1's "dataset" option to the simulation API's "data" option and API v1's "region" to API v2's "region." It also adds tests for all added/refactored methods.

Properly pass dataset into sim options, refactor

---

changelog_entry.yaml
gcp/policyengine_api/app.yaml
policyengine_api/data/data.py
policyengine_api/jobs/calculate_economy_simulation_job.py
policyengine_api/utils/v2_v1_comparison.py
setup.py
tests/fixtures/utils/v2_v1_comparison.py
tests/unit/utils/test_v2_v1_comparison.py

Fixes https://github.com/PolicyEngine/issues/issues/363
Fixes https://github.com/PolicyEngine/issues/issues/364
This code does the following:
* Rolls back the society-wide simulation code to use API v1 by default
* Increases the GCP resourcing for API v1 back to pre-v2 levels
* Re-enables running API v1 and v2 in tandem in order to compare results
* Adds a new logging structure designed to make it easy to programmatically pull the results from GCP for analysis and comparison
* Adds tests for the new structures
I was unable to test running the simulation API v2 workflow locally alongside the full API itself. Would love advice on configuration for that procedure moving forward.

Roll back simulation API to v1

---

changelog_entry.yaml
policyengine_api/jobs/calculate_economy_simulation_job.py
policyengine_api/utils/v2_v1_comparison.py
tests/fixtures/utils/v2_v1_comparison.py
tests/unit/utils/test_v2_v1_comparison.py

Fixes #2473.
This code uses updates to `.py` to add v1 and v2 country package versions to the objects we log to GCP.

Add v1 and v2 country package versions

---

changelog_entry.yaml
policyengine_api/jobs/calculate_economy_simulation_job.py
policyengine_api/utils/v2_v1_comparison.py
setup.py
tests/fixtures/jobs/calculate_economy_simulation_job.py
tests/unit/jobs/test_calculate_economy_simulation_job.py

Fixes #2476 
Fixes #2477 
- Added logging within `CalculateEconomySimulationJob.run()` to add semi-structured logging when API v1 fails
- Added a pinned update to `policyengine.py` version
- The first change allows for better regression testing by allowing us to catch cases where API v1 fails before being able to run a v2 comparison
- The second change ensures API v2 logging can properly identify the country package version present within workflow logs

Add logging for API v1 failures

---

changelog_entry.yaml
tests/unit/services/test_update_profile_service.py

Added test for update_profile method

---

changelog_entry.yaml
policyengine_api/services/ai_analysis_service.py

Fixes #2519.
- Temporarily downgraded Claude to 3.5 Sonnet
- Claude 4.0 sometimes inserts unwanted quotes into Explain with AI outputs (see https://github.com/PolicyEngine/policyengine-app/issues/2584); we don't want to fully downgrade from Claude 4.0, but we want to temporarily prevent the quotes issue, then re-upgrade and add a more durable fix.
N/A

Temporarily downgrade Claude to 3.5 Sonnet

---

.github/request-model-versions.sh
changelog_entry.yaml

Fixes #2530 
Adds a Bash script to invoke the simulation API's `wait_for_country_version" Google Cloud workflow. This workflow uses a polling structure to asynchronously determine the simulation API's model versions and return SUCCESS if they match the ones provided to the script, or to fail if not. 
In a future PR, I will run this script as part of a Google Cloud workflow, passing in the API deployment's model versions.

Add script to request model versions

---

changelog_entry.yaml
policyengine_api/jobs/calculate_economy_simulation_job.py
policyengine_api/utils/hugging_face.py

Fix Pass data and country package versions to APIv2 #2500

---

changelog_entry.yaml
policyengine_api/jobs/calculate_economy_simulation_job.py
policyengine_api/utils/v2_v1_comparison.py
tests/fixtures/utils/v2_v1_comparison.py
tests/unit/jobs/test_calculate_economy_simulation_job.py
tests/unit/utils/test_v2_v1_comparison.py

Fixes #2538.
Adds logging at various points within the `CalculateEconomySimulationJob`.

Improve logging

---

changelog_entry.yaml
policyengine_api/jobs/calculate_economy_simulation_job.py
tests/to_refactor/python/test_us_policy_macro.py

Fixes #2544
Requires https://github.com/PolicyEngine/policyengine-core/actions/runs/15472723999/job/43560964713?pr=370

2023 CPS is uprated one year too few

---

changelog_entry.yaml
policyengine_api/jobs/calculate_economy_simulation_job.py

Fixes #2566 
Properly pass args to API v1's run method to prevent error we're currently getting. This passes locally. Tests not added, since we aim to remove this feature by Monday of next week.

Properly pass args to API v1 run method

---

.env.example
.github/setup_env.sh
Makefile
changelog_entry.yaml

Created an example environment variable file

---

changelog_entry.yaml
policyengine_api/jobs/calculate_economy_simulation_job.py
policyengine_api/routes/economy_routes.py
policyengine_api/services/economy_service.py
tests/unit/jobs/test_calculate_economy_simulation_job.py

Fixes #2605.
Does not need to be merged before handling https://github.com/PolicyEngine/policyengine-app/issues/2620. Will include screenshot of cliff impacts working in the PR opened to fix that issue.
This PR makes modifications to the `CalculateEconomySimulationJob` and the economy router and service to take the `target` URL parameter, check if it is equal to `cliff`, then pass that into the simulation API via the Boolean `include_cliffs` argument created as part of `.py`. It also makes minor typing fixes and code quality improvements.
This PR adds a test for the `SimulationAPI` class to ensure proper setup, but it does not add a test for the `CalculateEconomySimulationJob` class. I'm hoping to add more comprehensive testing as part of …

Properly pass arguments from API call to request cliff impacts

---

changelog_entry.yaml
gcp/policyengine_api/app.yaml

Fixes #2615.
This PR increases the GCP readiness check success threshold from 400 seconds to 600. This is meant to prevent deployment failures like the one flagged in the original issue.

Increase GCP timeout

---

changelog_entry.yaml
tests/unit/services/test_create_profile.py

Created test_create_profile.py

---

changelog_entry.yaml
policyengine_api/data/model_setup.py

Partially addresses https://github.com/PolicyEngine/policyengine-api-v2/issues/297.
Updates the standard FRS address to the 2023-24 version.

Upgrade FRS to 2023-24 version

---

changelog_entry.yaml
gcp/policyengine_api/app.yaml
gcp/policyengine_api/start.sh

Fixes #2182 
Uses gunicorn's "preload" feature to avoid causing 100% CPU utilization on boot. Modifies readiness checks to match liveness checks.

Use gunicorn preload option, modify readiness checks
