PolicyEngine/policyengine-api

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.56.3

Update PolicyEngine UK to 0.56.3

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.498.0

Update PolicyEngine US to 0.498.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.499.0

Update PolicyEngine US to 0.499.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.56.4

Update PolicyEngine UK to 0.56.4

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.501.0

Update PolicyEngine US to 0.501.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.501.1

Update PolicyEngine US to 0.501.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.502.0

Update PolicyEngine US to 0.502.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.502.1

Update PolicyEngine US to 0.502.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.503.1

Update PolicyEngine US to 0.503.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.57.0

Update PolicyEngine UK to 0.57.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.506.1

Update PolicyEngine US to 0.506.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.508.1

Update PolicyEngine US to 0.508.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.508.2

Update PolicyEngine US to 0.508.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.508.3

Update PolicyEngine US to 0.508.3

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.509.0

Update PolicyEngine US to 0.509.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.58.1

Update PolicyEngine UK to 0.58.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.511.0

Update PolicyEngine US to 0.511.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.512.0

Update PolicyEngine US to 0.512.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.513.0

Update PolicyEngine US to 0.513.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.514.0

Update PolicyEngine US to 0.514.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.514.1

Update PolicyEngine US to 0.514.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.514.2

Update PolicyEngine US to 0.514.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.515.0

Update PolicyEngine US to 0.515.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.516.2

Update PolicyEngine US to 0.516.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.516.3

Update PolicyEngine US to 0.516.3

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.518.1

Update PolicyEngine US to 0.518.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.518.3

Update PolicyEngine US to 0.518.3

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.518.5

Update PolicyEngine US to 0.518.5

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.519.0

Update PolicyEngine US to 0.519.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.523.1

Update PolicyEngine US to 0.523.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.526.0

Update PolicyEngine US to 0.526.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.527.0

Update PolicyEngine US to 0.527.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.87.0

Update PolicyEngine CANADA to 0.87.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.528.0

Update PolicyEngine US to 0.528.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.529.0

Update PolicyEngine US to 0.529.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.532.0

Update PolicyEngine US to 0.532.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.534.0

Update PolicyEngine US to 0.534.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.58.2

Update PolicyEngine UK to 0.58.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.535.1

Update PolicyEngine US to 0.535.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.536.0

Update PolicyEngine US to 0.536.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.536.1

Update PolicyEngine US to 0.536.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.537.1

Update PolicyEngine US to 0.537.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.60.0

Update PolicyEngine UK to 0.60.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.61.1

Update PolicyEngine UK to 0.61.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.538.0

Update PolicyEngine US to 0.538.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.538.1

Update PolicyEngine US to 0.538.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.540.0

Update PolicyEngine US to 0.540.0

---

changelog_entry.yaml
setup.py

Bump policyengine-uk now that -us supports latest -core

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.541.1

Update PolicyEngine US to 0.541.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.62.0

Update PolicyEngine UK to 0.62.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.558.0

Update PolicyEngine US to 0.558.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.558.1

Update PolicyEngine US to 0.558.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.560.0

Update PolicyEngine US to 0.560.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.563.0

Update PolicyEngine US to 0.563.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.571.2

Update PolicyEngine US to 0.571.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.580.0

Update PolicyEngine US to 0.580.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.583.0

Update PolicyEngine US to 0.583.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.584.0

Update PolicyEngine US to 0.584.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.584.1

Update PolicyEngine US to 0.584.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.585.0

Update PolicyEngine US to 0.585.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.586.2

Update PolicyEngine US to 0.586.2

---

changelog_entry.yaml
policyengine_api/country.py
setup.py

Update PolicyEngine US to 0.595.0

Update PolicyEngine US to 0.595.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.598.0

Update PolicyEngine US to 0.598.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.600.0

Update PolicyEngine US to 0.600.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.600.1

Update PolicyEngine US to 0.600.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.601.1

Update PolicyEngine US to 0.601.1

---

.github/workflows/pr.yml
.github/workflows/push.yml
changelog_entry.yaml
docker/Dockerfile

This PR will add automatic docker container deployment for each new API version

Add docker steps

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.603.0

Update PolicyEngine US to 0.603.0

---

changelog_entry.yaml
policyengine_api/endpoints/economy/compare.py

Fix state revenue impact double-counting

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.610.1

Update PolicyEngine US to 0.610.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.614.0

Update PolicyEngine US to 0.614.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.617.0

Update PolicyEngine US to 0.617.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.619.0

Update PolicyEngine US to 0.619.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.622.1

Update PolicyEngine US to 0.622.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.627.0

Update PolicyEngine US to 0.627.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.629.2

Update PolicyEngine US to 0.629.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.631.0

Update PolicyEngine US to 0.631.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.632.0

Update PolicyEngine US to 0.632.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.65.0

Update PolicyEngine UK to 0.65.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.635.0

Update PolicyEngine US to 0.635.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.637.2

Update PolicyEngine US to 0.637.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.637.4

Update PolicyEngine US to 0.637.4

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.644.0

Update PolicyEngine US to 0.644.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.648.3

Update PolicyEngine US to 0.648.3

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.654.1

Update PolicyEngine US to 0.654.1

---

Makefile
changelog_entry.yaml
tests/api/test_us_create_empty_policy.yaml
tests/python/test_data.py
tests/python/test_policy.py

Fix policy test

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.669.0

Update PolicyEngine US to 0.669.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.675.0

Update PolicyEngine US to 0.675.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.676.0

Update PolicyEngine US to 0.676.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.682.0

Update PolicyEngine US to 0.682.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.683.1

Update PolicyEngine US to 0.683.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.684.0

Update PolicyEngine US to 0.684.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.688.1

Update PolicyEngine US to 0.688.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.69.1

Update PolicyEngine UK to 0.69.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.688.2

Update PolicyEngine US to 0.688.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.70.0

Update PolicyEngine UK to 0.70.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.691.1

Update PolicyEngine US to 0.691.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.696.0

Update PolicyEngine US to 0.696.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.699.0

Update PolicyEngine US to 0.699.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.699.2

Update PolicyEngine US to 0.699.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.700.0

Update PolicyEngine US to 0.700.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.703.0

Update PolicyEngine US to 0.703.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.707.0

Update PolicyEngine US to 0.707.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.708.0

Update PolicyEngine US to 0.708.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.708.3

Update PolicyEngine US to 0.708.3

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.708.4

Update PolicyEngine US to 0.708.4

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.710.1

Update PolicyEngine US to 0.710.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.712.0

Update PolicyEngine US to 0.712.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.713.0

Update PolicyEngine US to 0.713.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.713.1

Update PolicyEngine US to 0.713.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.713.3

Update PolicyEngine US to 0.713.3

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.715.0

Update PolicyEngine US to 0.715.0

---

Makefile
changelog_entry.yaml

test: Increase test timeout to 350 seconds

---

changelog_entry.yaml
tests/python/test_economy_1.py

Disable test_economy_1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.717.0

Update PolicyEngine US to 0.717.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.727.1

Update PolicyEngine US to 0.727.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.727.2

Update PolicyEngine US to 0.727.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.728.0

Update PolicyEngine US to 0.728.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.733.1

Update PolicyEngine US to 0.733.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.737.0

Update PolicyEngine US to 0.737.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.737.1

Update PolicyEngine US to 0.737.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.739.0

Update PolicyEngine US to 0.739.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.73.1

Update PolicyEngine UK to 0.73.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.743.1

Update PolicyEngine US to 0.743.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.95.0

Update PolicyEngine CANADA to 0.95.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.748.0

Update PolicyEngine US to 0.748.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.750.0

Update PolicyEngine US to 0.750.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.752.0

Update PolicyEngine US to 0.752.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.753.0

Update PolicyEngine US to 0.753.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.754.0

Update PolicyEngine US to 0.754.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.74.1

Update PolicyEngine UK to 0.74.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.75.0

Update PolicyEngine UK to 0.75.0

---

changelog_entry.yaml
policyengine_api/endpoints/economy/compare.py
policyengine_api/endpoints/economy/single_economy.py
setup.py

Add revenue impact of LSRs to economic outputs

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.760.0

Update PolicyEngine US to 0.760.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.761.0

Update PolicyEngine US to 0.761.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.763.0

Update PolicyEngine US to 0.763.0

---

changelog_entry.yaml
policyengine_api/endpoints/economy/single_economy.py

Unfreeze state taxes in US simulations

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.766.0

Update PolicyEngine US to 0.766.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.767.0

Update PolicyEngine US to 0.767.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.776.0

Update PolicyEngine US to 0.776.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.77.0

Update PolicyEngine UK to 0.77.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.777.3

Update PolicyEngine US to 0.777.3

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.78.0

Update PolicyEngine UK to 0.78.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.79.0

Update PolicyEngine UK to 0.79.0

---

changelog_entry.yaml
policyengine_api/endpoints/economy/compare.py
policyengine_api/endpoints/economy/single_economy.py

Change LSR calculation to use baseline earnings instead of household market income

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.779.2

Update PolicyEngine US to 0.779.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.80.0

Update PolicyEngine UK to 0.80.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.780.2

Update PolicyEngine US to 0.780.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.783.0

Update PolicyEngine US to 0.783.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.785.0

Update PolicyEngine US to 0.785.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.785.1

Update PolicyEngine US to 0.785.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.82.0

Update PolicyEngine UK to 0.82.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.787.0

Update PolicyEngine US to 0.787.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.788.0

Update PolicyEngine US to 0.788.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.791.0

Update PolicyEngine US to 0.791.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.792.0

Update PolicyEngine US to 0.792.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.794.2

Update PolicyEngine US to 0.794.2

---

changelog_entry.yaml
policyengine_api/endpoints/analysis.py

Switch to Claude 3.5 Sonnet

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 0.796.0

Update PolicyEngine US to 0.796.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.83.2

Update PolicyEngine UK to 0.83.2

---

.github/workflows/pr.yml
.github/workflows/push.yml
changelog_entry.yaml
docker/Dockerfile
gcp/Dockerfile
gcp/policyengine_api/start.sh

Fixes #1600. This PR temporarily downgrades to Python 3.9, pending further information regarding how to launch updates to the app's Dockerfile.

Temporarily downgrade to Python 3.9

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.84.0

Update PolicyEngine UK to 0.84.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 0.85.0

Update PolicyEngine UK to 0.85.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.8.0

Update PolicyEngine US to 1.8.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.12.0

Update PolicyEngine US to 1.12.0

---

.github/workflows/pr.yml
changelog_entry.yaml
gcp/policyengine_api/app.yaml
setup.py

Update PolicyEngine US to 1.16.0

Update PolicyEngine US to 1.16.0

---

.github/workflows/pr.yml
.github/workflows/push.yml
CHANGELOG.md
changelog.yaml
changelog_entry.yaml
docker/Dockerfile
gcp/Dockerfile
gcp/README.md
gcp/policyengine_api/app.yaml
gcp/policyengine_api/start.sh
policyengine_api/constants.py
setup.py

Update PolicyEngine US to 1.21.0

Update PolicyEngine US to 1.21.0

---

.github/workflows/pr.yml
.github/workflows/push.yml
CHANGELOG.md
changelog.yaml
changelog_entry.yaml
docker/Dockerfile
gcp/Dockerfile
gcp/README.md
gcp/policyengine_api/app.yaml
gcp/policyengine_api/start.sh
policyengine_api/constants.py
setup.py

Update PolicyEngine UK to 0.86.3

Update PolicyEngine UK to 0.86.3

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.22.0

Update PolicyEngine US to 1.22.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 1.0.0

Update PolicyEngine UK to 1.0.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.25.0

Update PolicyEngine US to 1.25.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.25.2

Update PolicyEngine US to 1.25.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.28.0

Update PolicyEngine US to 1.28.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.31.2

Update PolicyEngine US to 1.31.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.32.0

Update PolicyEngine US to 1.32.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.33.1

Update PolicyEngine US to 1.33.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.34.1

Update PolicyEngine US to 1.34.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 1.1.0

Update PolicyEngine UK to 1.1.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 1.3.0

Update PolicyEngine UK to 1.3.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.34.2

Update PolicyEngine US to 1.34.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.34.3

Update PolicyEngine US to 1.34.3

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.34.4

Update PolicyEngine US to 1.34.4

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 1.4.0

Update PolicyEngine UK to 1.4.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.34.5

Update PolicyEngine US to 1.34.5

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.34.7

Update PolicyEngine US to 1.34.7

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.35.0

Update PolicyEngine US to 1.35.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.37.0

Update PolicyEngine US to 1.37.0

---

changelog_entry.yaml
policyengine_api/endpoints/analysis.py

increase max tokens in claude ai summary

---

README.md
changelog_entry.yaml

Added instructions for new contributors to the README. 
Closes #1648

Update README 

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.39.0

Update PolicyEngine US to 1.39.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.42.1

Update PolicyEngine US to 1.42.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.44.1

Update PolicyEngine US to 1.44.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.45.1

Update PolicyEngine US to 1.45.1

---

.github/workflows/pr.yml
changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.45.2

Update PolicyEngine US to 1.45.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.50.0

Update PolicyEngine US to 1.50.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 1.7.0

Update PolicyEngine UK to 1.7.0

---

changelog_entry.yaml
gcp/policyengine_api/app.yaml
setup.py

Update PolicyEngine US to 1.51.1

Update PolicyEngine US to 1.51.1

---

changelog_entry.yaml
policyengine_api/country.py

Expand budgetary window in the US

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.52.0

Update PolicyEngine US to 1.52.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.54.1

Update PolicyEngine US to 1.54.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.54.2

Update PolicyEngine US to 1.54.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.54.3

Update PolicyEngine US to 1.54.3

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.55.0

Update PolicyEngine US to 1.55.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.56.1

Update PolicyEngine US to 1.56.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.57.0

Update PolicyEngine US to 1.57.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.57.1

Update PolicyEngine US to 1.57.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 1.7.1

Update PolicyEngine UK to 1.7.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.61.0

Update PolicyEngine US to 1.61.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.63.0

Update PolicyEngine US to 1.63.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.67.0

Update PolicyEngine US to 1.67.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.68.0

Update PolicyEngine US to 1.68.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.79.1

Update PolicyEngine US to 1.79.1

---

changelog_entry.yaml
policyengine_api/endpoints/economy/single_economy.py

Use the 2024 CPS in the compute_economy function

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.80.0

Update PolicyEngine US to 1.80.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.81.0

Update PolicyEngine US to 1.81.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.85.3

Update PolicyEngine US to 1.85.3

---

changelog_entry.yaml
policyengine_api/endpoints/analysis.py

Fixes: #419 
Added check for invalid country ID to return 404

Check for invalid/malformed country ID in get_analysis endpoint

---

changelog_entry.yaml
policyengine_api/endpoints/economy/single_economy.py
setup.py

Update PolicyEngine US to 1.89.0

Update PolicyEngine US to 1.89.0

---

changelog_entry.yaml
policyengine_api/data/data.py
policyengine_api/endpoints/economy/single_economy.py

Streamlined the economy code a little bit, and also implemented true subsetting (now, we're actually computing a subset rather than just zero-weighting it).

Fix issue with pooled CPS data

---

Makefile
changelog_entry.yaml
policyengine_api/endpoints/economy/single_economy.py
policyengine_api/endpoints/household.py
tests/python/data/or_rebate_measure_118.json
tests/python/test_or_rebate.py

Fixes #1821. Adds tests based upon the Oregon Rebate, aka Measure 118.

Add Oregon Rebate tests

---

Makefile
changelog_entry.yaml
policyengine_api/api.py
policyengine_api/data/initialise_local.sql
policyengine_api/endpoints/__init__.py
policyengine_api/endpoints/economy/economy.py
policyengine_api/endpoints/economy/reform_impact.py
policyengine_api/endpoints/economy/single_economy.py
policyengine_api/endpoints/simulation.py
tests/python/test_or_rebate.py

Adds a new /simulations endpoint

Improve status reporting

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.93.0

Update PolicyEngine US to 1.93.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.103.0

Update PolicyEngine US to 1.103.0

---

changelog_entry.yaml
setup.py

Fixes #1740.
Every time I try installing this thing in a new env, I have to manually delete this line in order to get the install to finish.

Remove grpcio pin

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.114.0

Update PolicyEngine US to 1.114.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.115.0

Update PolicyEngine US to 1.115.0

---

changelog_entry.yaml
tests/python/test_varying_your_earnings.py

Fixes #1847.
Note: This test should fail until https://github.com/PolicyEngine/policyengine-core/pull/288 is merged.

Add test for "Varying your earnings" chart

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.117.0

Update PolicyEngine US to 1.117.0

---

changelog_entry.yaml

Update PolicyEngine UK to 2.1.1

Update PolicyEngine UK to 2.1.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.127.0

Update PolicyEngine US to 1.127.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 2.2.0

Update PolicyEngine UK to 2.2.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 2.4.0

Update PolicyEngine UK to 2.4.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 2.6.0

Update PolicyEngine UK to 2.6.0

---

changelog_entry.yaml
policyengine_api/endpoints/economy/single_economy.py
setup.py

Change UK revenue metric

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 2.8.0

Update PolicyEngine UK to 2.8.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.129.3

Update PolicyEngine US to 1.129.3

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 2.9.0

Update PolicyEngine UK to 2.9.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 2.10.0

Update PolicyEngine UK to 2.10.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 2.11.0

Update PolicyEngine UK to 2.11.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 2.12.0

Update PolicyEngine UK to 2.12.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 2.13.0

Update PolicyEngine UK to 2.13.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 2.13.1

Update PolicyEngine UK to 2.13.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.133.0

Update PolicyEngine US to 1.133.0

---

.github/workflows/pr.yml
.github/workflows/push.yml
changelog_entry.yaml
docker/Dockerfile
gcp/Dockerfile
gcp/policyengine_api/start.sh

Update python version to 3.11 on API and GCP

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 2.13.2

Update PolicyEngine UK to 2.13.2

---

.github/workflows/pr.yml
.github/workflows/push.yml
changelog_entry.yaml
docker/Dockerfile
gcp/Dockerfile
gcp/policyengine_api/start.sh
policyengine_api/data/data.py
setup.py

Update PolicyEngine UK to 2.14.0

Update PolicyEngine UK to 2.14.0

---

changelog_entry.yaml
policyengine_api/data/data.py

Revert previous db change; don't use local db in prod

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.136.0

Update PolicyEngine US to 1.136.0

---

.github/workflows/pr.yml
.gitignore
changelog_entry.yaml

Switch to `google-github-actions/auth` from `service account key`

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.136.1

Update PolicyEngine US to 1.136.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.136.2

Update PolicyEngine US to 1.136.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 2.14.1

Update PolicyEngine UK to 2.14.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 2.15.0

Update PolicyEngine UK to 2.15.0

---

changelog_entry.yaml
gcp/policyengine_api/app.yaml
policyengine_api/endpoints/economy/single_economy.py
setup.py

Update PolicyEngine US to 1.137.2

Update PolicyEngine US to 1.137.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.137.3

Update PolicyEngine US to 1.137.3

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.137.4

Update PolicyEngine US to 1.137.4

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 2.15.1

Update PolicyEngine UK to 2.15.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.142.2

Update PolicyEngine US to 1.142.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.144.0

Update PolicyEngine US to 1.144.0

---

changelog_entry.yaml
policyengine_api/endpoints/economy/compare.py

Americanize country agnostic code

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.150.0

Update PolicyEngine US to 1.150.0

---

changelog_entry.yaml
policyengine_api/jobs/tasks/compute_general_economy.py

Remove undefined state tax reference

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 2.16.0

Update PolicyEngine UK to 2.16.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.154.1

Update PolicyEngine US to 1.154.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 2.17.0

Update PolicyEngine UK to 2.17.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.160.0

Update PolicyEngine US to 1.160.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.161.1

Update PolicyEngine US to 1.161.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.161.2

Update PolicyEngine US to 1.161.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.162.0

Update PolicyEngine US to 1.162.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.164.0

Update PolicyEngine US to 1.164.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.166.0

Update PolicyEngine US to 1.166.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.167.0

Update PolicyEngine US to 1.167.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.167.1

Update PolicyEngine US to 1.167.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.168.0

Update PolicyEngine US to 1.168.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.172.0

Update PolicyEngine US to 1.172.0

---

README.md
changelog_entry.yaml

Update README to describe method to run worker in debug mode

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.176.1

Update PolicyEngine US to 1.176.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.176.2

Update PolicyEngine US to 1.176.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.180.0

Update PolicyEngine US to 1.180.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.180.1

Update PolicyEngine US to 1.180.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.181.0

Update PolicyEngine US to 1.181.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.182.0

Update PolicyEngine US to 1.182.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.183.1

Update PolicyEngine US to 1.183.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.187.0

Update PolicyEngine US to 1.187.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.187.1

Update PolicyEngine US to 1.187.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.187.2

Update PolicyEngine US to 1.187.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.195.0

Update PolicyEngine US to 1.195.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.196.1

Update PolicyEngine US to 1.196.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.197.0

Update PolicyEngine US to 1.197.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.200.0

Update PolicyEngine US to 1.200.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.200.1

Update PolicyEngine US to 1.200.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.201.0

Update PolicyEngine US to 1.201.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.202.0

Update PolicyEngine US to 1.202.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.202.1

Update PolicyEngine US to 1.202.1

---

changelog_entry.yaml
policyengine_api/jobs/calculate_economy_simulation_job.py

Fix UK country filtering

---

changelog_entry.yaml
policyengine_api/country.py

Fix bug causing specific scale parameters to fail when changed

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.202.2

Update PolicyEngine US to 1.202.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.203.1

Update PolicyEngine US to 1.203.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 2.20.0

Update PolicyEngine UK to 2.20.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.204.0

Update PolicyEngine US to 1.204.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.205.0

Update PolicyEngine US to 1.205.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.207.0

Update PolicyEngine US to 1.207.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.208.0

Update PolicyEngine US to 1.208.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.209.1

Update PolicyEngine US to 1.209.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.213.1

Update PolicyEngine US to 1.213.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 2.22.1

Update PolicyEngine UK to 2.22.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 2.22.2

Update PolicyEngine UK to 2.22.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.226.0

Update PolicyEngine US to 1.226.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 2.22.4

Update PolicyEngine UK to 2.22.4

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 2.22.6

Update PolicyEngine UK to 2.22.6

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.240.1

Update PolicyEngine US to 1.240.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 2.22.8

Update PolicyEngine UK to 2.22.8

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.240.5

Update PolicyEngine US to 1.240.5

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.245.0

Update PolicyEngine US to 1.245.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.247.0

Update PolicyEngine US to 1.247.0

---

changelog_entry.yaml
policyengine_api/jobs/calculate_economy_simulation_job.py

Adjust API v2/v1 comparison function

---

changelog_entry.yaml
setup.py

Re-pin -core to 3.16.6

---

changelog_entry.yaml
gcp/policyengine_api/app.yaml
policyengine_api/jobs/calculate_economy_simulation_job.py

Migrate to APIv2 for economic impacts

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.265.0

Update PolicyEngine US to 1.265.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 2.24.2

Update PolicyEngine UK to 2.24.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.269.0

Update PolicyEngine US to 1.269.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.270.0

Update PolicyEngine US to 1.270.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.272.0

Update PolicyEngine US to 1.272.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.276.0

Update PolicyEngine US to 1.276.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.280.1

Update PolicyEngine US to 1.280.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.282.1

Update PolicyEngine US to 1.282.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.287.0

Update PolicyEngine US to 1.287.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.288.0

Update PolicyEngine US to 1.288.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.289.0

Update PolicyEngine US to 1.289.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.289.1

Update PolicyEngine US to 1.289.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine UK to 2.28.1

Update PolicyEngine UK to 2.28.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.299.1

Update PolicyEngine US to 1.299.1

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.300.0

Update PolicyEngine US to 1.300.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.302.0

Update PolicyEngine US to 1.302.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.307.0

Update PolicyEngine US to 1.307.0

---

changelog_entry.yaml
setup.py
tests/data/uk_household.json

Fix tests and update country packages

---

.github/workflows/push.yml
changelog_entry.yaml

Created automatic tag release

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.320.0

Update PolicyEngine US to 1.320.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.327.0

Update PolicyEngine US to 1.327.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.327.2

Update PolicyEngine US to 1.327.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.331.0

Update PolicyEngine US to 1.331.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.334.0

Update PolicyEngine US to 1.334.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.337.0

Update PolicyEngine US to 1.337.0

---

.github/wait-for-pypi.sh
.github/workflows/pr.yml
.github/workflows/push.yml
changelog_entry.yaml

Fixed flaky test by adding retry for policyengine_us version availability on PyPI

---

changelog_entry.yaml
setup.py

Update PolicyEngine CANADA to 0.96.3
Fix #2672

Update PolicyEngine CANADA to 0.96.3 and microdf to >1.0.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.366.2

Update PolicyEngine US to 1.366.2

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.369.0

Update PolicyEngine US to 1.369.0

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.395.1

Update PolicyEngine US to 1.395.1

---

changelog_entry.yaml
gcp/policyengine_api/app.yaml

Fix app.yaml timeout key

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.407.3

Update PolicyEngine US to 1.407.3

---

changelog_entry.yaml
setup.py

Update PolicyEngine US to 1.408.1

Update PolicyEngine US to 1.408.1
